modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
[[mods]]
modId="cmsrenewable"
version="${file.jarVersion}"
displayName="CMS Renewable"
logoFile="CMSRenewable.png"
authors="CMS"
credits="CMS resource renewable"
description='''
Create makes resources reproducible in the CMS!
'''
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
